import "server-only";
import type { createServiceClient } from "@/lib/supabase/service";

type ServiceClient = ReturnType<typeof createServiceClient>;

/** Private bucket, created by supabase/migrations/0025_job_docs.sql
 * (public: false, no RLS policy granted to `authenticated`) — the
 * service role is the only writer and the only reader; the dashboard
 * gets in only via a server-generated signed URL, after the requesting
 * owner's own RLS-scoped job_docs lookup already proved ownership. */
const BUCKET = "job-doc-media";

const EXTENSION_BY_MIME: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

/**
 * Stores one job-record photo, scoped by business and job doc so the
 * path itself carries no ambiguity about whose data it is — keyed by
 * the photo's own id (generated by the caller before this runs).
 */
export async function storeJobDocPhoto(
  supabase: ServiceClient,
  input: { businessId: string; jobDocId: string; photoId: string; bytes: Uint8Array; mimeType: string }
): Promise<string> {
  const extension = EXTENSION_BY_MIME[input.mimeType] ?? "bin";
  const path = `${input.businessId}/${input.jobDocId}/${input.photoId}.${extension}`;

  const { error } = await supabase.storage.from(BUCKET).upload(path, input.bytes, {
    contentType: input.mimeType,
    upsert: true,
  });
  if (error) throw new Error(`Failed to store job doc photo: ${error.message}`);

  return path;
}

export async function deleteJobDocPhoto(supabase: ServiceClient, storagePath: string): Promise<void> {
  const { error } = await supabase.storage.from(BUCKET).remove([storagePath]);
  if (error) throw new Error(`Failed to delete job doc photo: ${error.message}`);
}

/**
 * Re-reads an already-stored photo's bytes (Phase 2A retry fix) — the
 * original upload is never touched or re-uploaded; this only fetches
 * it back so analysis can run again against the same image.
 */
export async function downloadJobDocPhoto(
  supabase: ServiceClient,
  storagePath: string
): Promise<{ bytes: Uint8Array; mimeType: string }> {
  const { data, error } = await supabase.storage.from(BUCKET).download(storagePath);
  if (error || !data) throw new Error(`Failed to download job doc photo: ${error?.message ?? "no data returned"}`);
  const arrayBuffer = await data.arrayBuffer();
  return { bytes: new Uint8Array(arrayBuffer), mimeType: data.type || "image/jpeg" };
}

export { BUCKET as JOB_DOC_MEDIA_BUCKET };
