-- ReplyFlow — 0025: Job Docs foundation (ReplyFlow 2.0, step 1)
--
-- Four tables for the future Job Document flow (photo capture, AI
-- drafting, PDF generation, signing, sharing — all deliberately NOT
-- built yet). This migration only lays the schema + the minimal
-- create/list foundation needs; nothing here wires up those later
-- stages. Revised per GenSpark's architecture review (Approve With
-- Changes) before first apply — see each table's own comment for what
-- changed and why.
--
-- job_docs — the record itself. One flat, owner-editable row per job
-- document, same "add real structure when a real feature needs it"
-- reasoning already used for businesses/work_cards (see 0005_jobs.sql's
-- own comment) — no separate revision/history table until a real
-- feature needs one. conversation_id is optional (a Job Doc may or may
-- not have started from a real conversation) and never required.
-- status now has a real lifecycle check constraint (draft -> review ->
-- signed -> exported), per the approved architecture — the earlier,
-- pre-review version of this migration deliberately left it open;
-- GenSpark's review settled the lifecycle, so it's constrained now.
-- Customer/job/signing/export fields are added as plain nullable
-- columns (customer_name defaults to '' to keep an insert from a bare
-- title alone valid) — nothing populates the signing/export columns
-- yet, they exist so later phases don't need another migration just to
-- add them. RLS/grants follow work_cards exactly: this table has no
-- secret in it, so owners get full select/insert/update, not the
-- service-role-only pattern.
--
-- job_doc_fields — flexible, provenance-tracked fields captured
-- against a Job Doc (provenance/confidence is a core ReplyFlow
-- differentiator, per GenSpark's review — every field records whether
-- it came from the customer, was AI-structured, was only an AI
-- suggestion, or is still missing, plus how confident that was, plus
-- who last touched it). One row per field, denormalized business_id
-- for the same simpler-RLS reason 0003's own comment already gives for
-- messages/conversations. RLS changed from the original version of
-- this migration: owners get SELECT only now — every write goes
-- through a server-side route using the service role, after an
-- explicit auth/ownership check, the same boundary reply_drafts and
-- conversation_photos already use for pipeline-written data.
--
-- job_doc_photos — foundation only, nothing writes to this table yet
-- (photo capture is explicitly out of scope for this step). Mirrors
-- conversation_photos' (0024) own visible/possible/unknown analysis
-- shape directly, plus phase/sort_order for organising a job's photos
-- once that UI exists. Same owner-select-only / service-role-write
-- pattern as conversation_photos — customer/job media is treated as
-- sensitive by default here, not opened up until something real
-- actually needs owner-side writes.
--
-- job_doc_shares — foundation only, nothing writes to this table yet
-- (sharing is explicitly out of scope). Unchanged by this review pass
-- — share_token stays nullable with no default, generated by whichever
-- later migration/feature actually implements sharing. Column-
-- privileged the same way whatsapp_connections.access_token is (0018):
-- share_token is a bearer credential once it exists, so it's withheld
-- from `authenticated` from day one rather than opened up now and
-- locked down later.

create table if not exists public.job_docs (
  id               uuid primary key default gen_random_uuid(),
  business_id      uuid not null references public.businesses(id) on delete cascade,
  conversation_id  uuid references public.conversations(id) on delete set null,
  created_by       uuid references auth.users(id) on delete set null,

  title            text not null,
  status           text not null default 'draft'
                    check (status in ('draft', 'review', 'signed', 'exported')),
  template_type    text not null default 'job_summary',

  customer_name    text not null default '',
  customer_phone   text,
  customer_email   text,
  job_address      text,
  job_date         timestamptz,

  signed_by            text,
  signed_at            timestamptz,
  signature_statement  text,
  export_pdf_path      text,
  exported_at          timestamptz,

  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists job_docs_business_id_idx on public.job_docs (business_id);
create index if not exists job_docs_conversation_id_idx on public.job_docs (conversation_id);

drop trigger if exists set_job_docs_updated_at on public.job_docs;
create trigger set_job_docs_updated_at
  before update on public.job_docs
  for each row execute procedure public.set_updated_at();

alter table public.job_docs enable row level security;

drop policy if exists "Owners can view their own job docs" on public.job_docs;
create policy "Owners can view their own job docs"
  on public.job_docs for select
  using (business_id in (select id from public.businesses where owner_id = auth.uid()));

drop policy if exists "Owners can insert their own job docs" on public.job_docs;
create policy "Owners can insert their own job docs"
  on public.job_docs for insert
  with check (business_id in (select id from public.businesses where owner_id = auth.uid()));

drop policy if exists "Owners can update their own job docs" on public.job_docs;
create policy "Owners can update their own job docs"
  on public.job_docs for update
  using (business_id in (select id from public.businesses where owner_id = auth.uid()))
  with check (business_id in (select id from public.businesses where owner_id = auth.uid()));

grant select, insert, update on public.job_docs to authenticated;

-- ---------------------------------------------------------------------

create table if not exists public.job_doc_fields (
  id            uuid primary key default gen_random_uuid(),
  job_doc_id    uuid not null references public.job_docs(id) on delete cascade,
  business_id   uuid not null references public.businesses(id) on delete cascade,

  section_label text not null default '',
  sort_order    integer not null default 0,

  field_key     text not null,
  field_value   text,

  provenance    text not null default 'missing'
                 check (provenance in ('user_fact', 'ai_structured', 'ai_suggestion', 'missing')),
  confidence    text not null default 'none'
                 check (confidence in ('none', 'low', 'medium', 'high')),
  updated_by    text not null default 'ai'
                 check (updated_by in ('ai', 'engineer')),

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint job_doc_fields_job_doc_id_field_key_key unique (job_doc_id, field_key)
);

create index if not exists job_doc_fields_job_doc_id_idx on public.job_doc_fields (job_doc_id);
create index if not exists job_doc_fields_business_id_idx on public.job_doc_fields (business_id);

drop trigger if exists set_job_doc_fields_updated_at on public.job_doc_fields;
create trigger set_job_doc_fields_updated_at
  before update on public.job_doc_fields
  for each row execute procedure public.set_updated_at();

alter table public.job_doc_fields enable row level security;

drop policy if exists "Owners can view their own job doc fields" on public.job_doc_fields;
create policy "Owners can view their own job doc fields"
  on public.job_doc_fields for select
  using (business_id in (select id from public.businesses where owner_id = auth.uid()));

-- No insert/update policy or grant (GenSpark review) — job_doc_fields
-- carries provenance/confidence data that must only ever be written by
-- a controlled server-side route (service role, after an explicit
-- auth/ownership check), never directly from the browser. Same
-- boundary conversation_photos and job_doc_photos already use.
grant select on public.job_doc_fields to authenticated;

-- ---------------------------------------------------------------------

create table if not exists public.job_doc_photos (
  id            uuid primary key default gen_random_uuid(),
  job_doc_id    uuid not null references public.job_docs(id) on delete cascade,
  business_id   uuid not null references public.businesses(id) on delete cascade,

  storage_path  text not null,
  caption       text,
  phase         text not null default 'other'
                 check (phase in ('before', 'during', 'after', 'other')),
  sort_order    integer not null default 0,

  visible_summary      text not null default '',
  possible_summary     text not null default '',
  unknown_note         text not null default '',
  analysis_confidence  text not null default 'low'
                        check (analysis_confidence in ('low', 'medium', 'high')),

  created_at    timestamptz not null default now()
);

create index if not exists job_doc_photos_job_doc_id_idx on public.job_doc_photos (job_doc_id);
create index if not exists job_doc_photos_business_id_idx on public.job_doc_photos (business_id);

alter table public.job_doc_photos enable row level security;

drop policy if exists "Owners can view their own job doc photos" on public.job_doc_photos;
create policy "Owners can view their own job doc photos"
  on public.job_doc_photos for select
  using (business_id in (select id from public.businesses where owner_id = auth.uid()));

-- No insert/update policy: matching conversation_photos (0024), every
-- write happens server-side via the service role once the photo-capture
-- feature actually exists.
grant select on public.job_doc_photos to authenticated;

-- ---------------------------------------------------------------------

create table if not exists public.job_doc_shares (
  id            uuid primary key default gen_random_uuid(),
  job_doc_id    uuid not null references public.job_docs(id) on delete cascade,
  business_id   uuid not null references public.businesses(id) on delete cascade,

  share_token   text unique,
  expires_at    timestamptz,
  revoked_at    timestamptz,

  created_at    timestamptz not null default now()
);

create index if not exists job_doc_shares_job_doc_id_idx on public.job_doc_shares (job_doc_id);
create index if not exists job_doc_shares_business_id_idx on public.job_doc_shares (business_id);

alter table public.job_doc_shares enable row level security;

drop policy if exists "Owners can view their own job doc shares" on public.job_doc_shares;
create policy "Owners can view their own job doc shares"
  on public.job_doc_shares for select
  using (business_id in (select id from public.businesses where owner_id = auth.uid()));

-- Column-privileged the same way 0018 locks down whatsapp_connections.
-- access_token — share_token is a bearer credential once the sharing
-- feature exists, so it's withheld from `authenticated` from day one.
grant select (
  id,
  job_doc_id,
  business_id,
  expires_at,
  revoked_at,
  created_at
) on public.job_doc_shares to authenticated;

-- ---------------------------------------------------------------------

-- Private bucket, same convention as customer-media (0024): no RLS
-- policy granted to `authenticated` at all — the service role is the
-- only reader/writer once photo capture and sharing are actually built.
insert into storage.buckets (id, name, public)
values ('job-doc-media', 'job-doc-media', false)
on conflict (id) do nothing;

notify pgrst, 'reload schema';
